murders = [
'{name} shamed {victim} on Twitter to death', '{victim} didn\'t sleep when they were told to by {name}, and so suffered chaos\'s wrath.', 
'{victim} didnt have a drivers licencse {name} caught them and sent them to prison.', 
'{name} asked the reaper of death to reap {victim}\'s soul, safe to say, they are no longer in this world.', 
'{name} tricked {victim} into talking about SCP-●●|●●●●●|●●|●', 
'{victim} didn\'t ask {name} to DM and Thouit banned them', 
'{victim} died studying history by {name}', 
'{name} had the high ground against {victim} ', 
'{name} couldn\'t convince {victim} to stay and joined the dark side.', 
'{name} didn\'t trust {victim} at the bar and filled their drink with laxatives.', 
'{name} sent {victim} to the shadow realm as a sacrifice to the tentacles for Kat', 
'{victim} got ||redacted|| in {name} pocket dimension.', 
'{name} called NTF on {victim}', 
'{name} invited {victim} to chaos insurgency. That was a short visit.', 
'{victim} uses duck gun on {name}. {victim} shot themself.', 
'{name} explained what SCP-001 is to {victim}. victim got [data expunged]', 
'{victim} used to be an adventurer until {name} shot them in their knee.', 
'{name} paid Gabi to tease {victim}. {victim} died of sexual frustration.', 
'{name} likes trains. {victim} d- angry train noises', 
'{name} showed {victim} the most terrifying thing man has ever made. The mirror.', 
'{victim} regrets that their medical insurance didn\'t cover {name}\'s and potato\'s fusion.',
'{name} dared {victim} to fight god as a joke, they took it seriously',
'{name} did something lewd to {victim} and they blushed way too hard',
'{name} kisses {victim} on their cheek and they melted',
'{name} said they pour the milk before putting in the cereal to {victim}',
'{name} bent {victim} over a counter and now they can\'t sit for a week',
'{name} slapped {victim} very lightly and they exploded',
'{name} worked hard to ship Birdie Boy and {victim}, Squid Face killed {victim} due to jealousy',
'{name} sent {victim} lewd stuff at work. {victim} got too horny in front of their coworkers... and their boss.',
'{name} beat {victim} at chess. {victim} gained the permanent role of {name}\'s Simp.',
'{name} caught {victim} getting a little too intimate with Coin Machine.',
'{name} and {victim} found out they were both bottoms. {victim} was promptly punished for lying about being top.',
'{name} and {victim} were both being chased by a serial killer, but {name} ran faster.',
'{name} hacked the bot and made {victim} lose this round',
'{victim} made {name} laugh too hard while they were eating their last cookie. {name} proceeded to chase {victim} with a knife as payback.',
'{name} threw a custard pie in a random direction while blindfolded, and it hit {victim} square in the face. ',
'{name} forced {victim} to wear a tutu and perform on stage, {victim} died of embarassment.',
'{name} didn\'t do anything to {victim}. {victim} decided to be dramatic and blame it on them.',
'{name} grew a big fat futa member, {victim} got fucked in the ass by it and is now {name}\'s cock sleeve.',
'{name} used a magic spell and turned {victim} in a chicken',
'{name} used a wand in {victim}\'s throat to make them choke on it.',
'{name} convinced {victim} to use a cheesy pickup line on their crush.',
'{name} refused to lend {victim} their cellphone charger.',
'{name} ate {victim}\'s laptop because they were hungry. {victim} cried themselves to sleep.',
'{name} solemnly swears that none of the compromising screen shots of {victim} have been edited.',
'{name} didn\'t do anything to {victim}. {victim} decided to be dramatic and blame it on them.',
'{name} stole all of {victim}\'s cookies and they died of sadness',
'{name} fed {victim} too many black cookies',
'{name} got wayyyy too horni for {victim} and died',
'{name} buried {victim} in an avalanche of marshmallows',
'{name} put something where it wasnt supposed to go into {victim} and they ran away',
'{name} killed {victim} with L O V E !!!',
'{name} yeeted {victim} into a portal to Florida and was never seen again',
'{name} tied {victim} to a chair and they melted',
'{name} told {victim} to eat dirt ',
'{name} fed {victim} soap soup',
'{victim} didn’t find the end of the rainbow, instead they found {name} with a knife',
'{name} pointed out that a bad bot design put the server at risk, so {victim} was kicked',
'{victim} stole cookies from {name} and paid the price',
'{victim} didn’t like {name}’s spotify playlist',
'{name} showed {victim} what it\'s like to "fuck the rainbow, taste the rainbow"',
'{name} rickrolled {victim} who promptly died of embarrassment',
'{name} betrayed {victim} at the Tribal Council. {victim} was voted out.',
'{name} volunteered {victim} as tribute',
'{victim} was framed by {name}',
'"Et tu, {name}?" were {victim}\'s last words.',
'{victim} didn’t think {name} was scary enough',
'{name} took {victim} to snowwy\'s torture room',
'{name} force fed {victim} a bag full of jellybeans',
'{victim} tried to find an error in {name}’s novel and fuking died',
'{name} took the ‘dom’ role too far on {victim}',
'{name} cancelled {victim} on Twitter',
'{name} reaped {victim}\'s soul',
'{name} forced {victim} into a milking machine and got milked to end of their life.',
'{name} tied {victim} up and used all kind of toys on {victim}\'s body to leave them in a dark room with endless pleasure.',
'{name} ruined {victim}\'s orgasm with a command.',
'{victim} was on a walk when they bumped into a mad {name}. It didn\'t end well for {victim}.',
'{name} leads {victim} into their sex dungeon, {victim}\'s fear over took their feelings and flees.',
'{name} spelled {victim}\'s name wrong, {victim} died from cringe.',
'{name} had snu snu with {victim}, {victim} dies in pleasure. ',
'{name} tried sounding with {victim}, it didnt work out so {victim} died',
'{name} accidently grew a huge horse cock, {name} thrusted into {victim}\'s mouth without mercy.',
'{name} ate a forbidden fruit and got giant mommy milkers, {victim}\'s head got squished between them on accident. ',
'{name} didn\'t learned enough about bondage, {victim} faints away.',
'{victim} died due to {name} haunting their sleep every night. ',
'{victim}\'s belly got inflated by gallons of cum, {name} watched how {victim} suffers. ',
'{name} puts a collar around {victim}\'s neck and is now {name}\'s pet. ',
'{victim} died by simping on {name} too much.',
'{name} belly flopped on {victim}',
'{victim} didn’t receive there forklift certification from {name}',
'{name} blundered their woman to {name} and resigned.',
'{name} stole {victim} blankeys and {victim} froze to death.',
'{victim} became a diary cow for {name}',
'{name} revealed their true identity. {victim} died out of shock.',
'{victim} turned out to be a manhwa translator. {name} eradicated them for the atrocities done to English.',
'{name} messed up with {victim} bondage. The latter died due to asphyxiation.',
'{name} used {victim} only weakness. Banana bomb.',
'{name} made {victim} hold their knife.',
'{name} told {victim} that they like trains.',
'{victim} called a draw. {name} drew their gun. {name} was faster.',
'{name} explained the theory of ||redacted|| to {victim}. {victim} Died to excessive knowledge.',
'{victim} hugged SCP-173. {name} didn\'t see that cause they blinked.',
'{name} threw SCP-018. Fast. {victim} didn\'t doge.',
'{victim} got redacted by {name}',
'{name} put salt into {victim}\'s coffee',
'{name} trapped {victim} in SCP-3008, aka. IKEA.',
'{name} made {victim} stare at SCP-055 for too long. They died of old age without realising it.',
'{name} used SCP-272 to bind {victim} to their shadow.',
'{name} showed SCP-033 to {victim}. They instantly met their swift demise.',
'{name} volunteered {victim} as SCP-049\'s test subject.'
]
